import { ImageSourcePropType } from 'react-native'
import type { EnemySnap } from '@/shared/types'

const enemyImagesById: Record<string, ImageSourcePropType> = {
  B_ORC: require('../../../assets/enemy/orc_expedition_captain.png'),
  B_HOB: require('../../../assets/enemy/hobgoblin.png'),
  B001: require('../../../assets/enemy/gray_wolf.png'),
  B_SLIME: require('../../../assets/enemy/boss_slime.png'),
  B_LICH: require('../../../assets/enemy/necromancer_remains.png'),
  B_CANNON: require('../../../assets/enemy/defense_cannon.png'),
  E001: require('../../../assets/enemy/slime.png'),
  S001: require('../../../assets/enemy/slime.png'),
  E002: require('../../../assets/enemy/forest_mouse.png'),
  E003: require('../../../assets/enemy/wolf.png'),
  E004: require('../../../assets/enemy/thorn_squirrel.png'),
  UND001: require('../../../assets/enemy/skeleton_soldier.png'),
  UND002: require('../../../assets/enemy/zombie.png'),
  UND003: require('../../../assets/enemy/ghost.png'),
  UND004: require('../../../assets/enemy/skeleton_archer.png'),
  UND005: require('../../../assets/enemy/ghoul.png'),
  ORC002: require('../../../assets/enemy/orc_soldier.png'),
  ORC005: require('../../../assets/enemy/orc_brute.png'),
  HUM001: require('../../../assets/enemy/frontier_soldier.png'),
  HUM002: require('../../../assets/enemy/human_mage.png'),
  HUM003: require('../../../assets/enemy/frontier_archer.png'),
  HUM004: require('../../../assets/enemy/human_cleric.png'),
  HUM005: require('../../../assets/enemy/frontier_knight.png'),
  B_CAPTAIN: require('../../../assets/enemy/frontier_knight_captain.png'),
  B_TRAVELER: require('../../../assets/enemy/human_merchant.png'),
  B_HUM_GUARD: require('../../../assets/enemy/human_guard.png'),
  B_HUM_WARRIOR: require('../../../assets/enemy/human_warrior.png'),
  B_HUM_MAGE: require('../../../assets/enemy/human_mage.png'),
  B_HUM_CLERIC: require('../../../assets/enemy/human_cleric.png'),
  GOB001: require('../../../assets/enemy/goblin.png'),
  GOB002: require('../../../assets/enemy/goblin_thief.png'),
  GOB003: require('../../../assets/enemy/goblin_warrior.png'),
  GOB004: require('../../../assets/enemy/goblin_mage.png'),
  GOB005: require('../../../assets/enemy/goblin_guard.png'),
  LIZ001: require('../../../assets/enemy/lizardman.png'),
  LIZ002: require('../../../assets/enemy/assassin_lizard.png'),
  LIZ004: require('../../../assets/enemy/armored_lizardman.png'),
  B_SWAMPKING: require('../../../assets/enemy/king_lizardman.png'),
  SPF003: require('../../../assets/enemy/arachne.png'),
  B_ARACHNE: require('../../../assets/enemy/queen_arachne.png'),
  HRP001: require('../../../assets/enemy/harpy.png'),
  B_HARPY_MATRIARCH: require('../../../assets/enemy/queen_harpy.png'),
  WFG001: require('../../../assets/enemy/wolf.png'),
  WFG002: require('../../../assets/enemy/dire_wolf.png'),
  WFG003: require('../../../assets/enemy/gray_wolf.png'),
  B_WOLF_ALPHA: require('../../../assets/enemy/grand_dire_wolf.png'),
  CAT001: require('../../../assets/enemy/cat_shadow_scout.png'),
  CAT002: require('../../../assets/enemy/cat_moonfang_duelist.png'),
  B_CAT_SHADOWLORD: require('../../../assets/enemy/cat_shadowlord_nekomata.png'),
  RD001: require('../../../assets/enemy/roadside_wolf.png'),
  RD002: require('../../../assets/enemy/giant_snake.png'),
  RD003: require('../../../assets/enemy/giant_scorpion.png'),
  VIL001: require('../../../assets/enemy/village_militia.png'),
  VIL002: require('../../../assets/enemy/village_guard.png'),
  VIL003: require('../../../assets/enemy/village_hunter.png'),
}

const enemyImagesByName: Record<string, ImageSourcePropType> = {
  オーク遠征隊長: enemyImagesById.B_ORC,
  ホブゴブリン: enemyImagesById.B_HOB,
  グレイウルフ: enemyImagesById.B001,
  ボススライム: enemyImagesById.B_SLIME,
  死霊術師の残骸: enemyImagesById.B_LICH,
  防衛砲台: enemyImagesById.B_CANNON,
  スライム: enemyImagesById.E001,
  森ネズミ: enemyImagesById.E002,
  ウルフ: enemyImagesById.E003,
  トゲリス: enemyImagesById.E004,
  スケルトン兵: enemyImagesById.UND001,
  ゾンビ: enemyImagesById.UND002,
  ゴースト: enemyImagesById.UND003,
  骨弓兵: enemyImagesById.UND004,
  屍鬼: enemyImagesById.UND005,
  オーク兵: enemyImagesById.ORC002,
  オークブルート: enemyImagesById.ORC005,
  辺境城正規兵: enemyImagesById.HUM001,
  辺境城魔術師: enemyImagesById.HUM002,
  辺境城弓兵: enemyImagesById.HUM003,
  辺境城クレリック: enemyImagesById.HUM004,
  辺境城騎士: enemyImagesById.HUM005,
  辺境城騎士団長: enemyImagesById.B_CAPTAIN,
  護衛付きの商人: enemyImagesById.B_TRAVELER,
  護衛ガード: enemyImagesById.B_HUM_GUARD,
  護衛ウォリアー: enemyImagesById.B_HUM_WARRIOR,
  護衛メイジ: enemyImagesById.B_HUM_MAGE,
  護衛クレリック: enemyImagesById.B_HUM_CLERIC,
  ゴブリン: enemyImagesById.GOB001,
  ゴブリンシーフ: enemyImagesById.GOB002,
  ゴブリンウォリアー: enemyImagesById.GOB003,
  ゴブリンメイジ: enemyImagesById.GOB004,
  ゴブリンガード: enemyImagesById.GOB005,
  リザードマン: enemyImagesById.LIZ001,
  アサシンリザード: enemyImagesById.LIZ002,
  重装リザードマン: enemyImagesById.LIZ004,
  キングリザードマン: enemyImagesById.B_SWAMPKING,
  アラクネ: enemyImagesById.SPF003,
  クイーンアラクネ: enemyImagesById.B_ARACHNE,
  ハーピィ: enemyImagesById.HRP001,
  クイーンハーピィ: enemyImagesById.B_HARPY_MATRIARCH,
  草原ウルフ: enemyImagesById.WFG001,
  ダイアウルフ: enemyImagesById.WFG002,
  牙王の眷属: enemyImagesById.WFG003,
  銀牙のアルファ: enemyImagesById.B_WOLF_ALPHA,
  グランダイアウルフ: enemyImagesById.B_WOLF_ALPHA,
  影爪の斥候: enemyImagesById.CAT001,
  月牙の双刃兵: enemyImagesById.CAT002,
  月影の遺跡主ネコマタ: enemyImagesById.B_CAT_SHADOWLORD,
  街道オオカミ: enemyImagesById.RD001,
  ジャイアントスネーク: enemyImagesById.RD002,
  ジャイアントスコーピオン: enemyImagesById.RD003,
  民兵: enemyImagesById.VIL001,
  村守備兵: enemyImagesById.VIL002,
  猟師: enemyImagesById.VIL003,
}

export function getEnemyImage(enemy: Pick<EnemySnap, 'id' | 'name'>): ImageSourcePropType | null {
  return enemyImagesById[enemy.id] ?? enemyImagesByName[enemy.name] ?? null
}
